---
layout: cv
title: Nathaniel L. Welling's CV
---


# Nate L. Welling

<div id="webaddress">
<a href="mailto:natewelling03@gmail.com">natewelling03@gmail.com</a> 
</div>

---

## Currently

Absorbing code, learning how machine learning works, cooking and sewing ties

### Specialized in

• CSS3 + HTML5  
• C# 
• python minecraft bots

---


## Experience

### Kitchen & Service Associate  
`September 2023 – Present`  
**Zip’s Drive-In**, Colfax, WA  
- Served ~75 hungry humans a day, headset hero and counter champion.  
- Commanded the grill, cooked 100+ patties daily with sizzling precision.

### Missionary  
`September 2021 – September 2023`  
**The Church of Jesus Christ of Latter-day Saints**, Cochabamba, Bolivia  
- Evangelized with fire and humility—contacted 30+ people daily to teach about Christ.  
- Led, trained, and spiritually fueled squads of up to 10 missionaries.

### Facilities Maintenance  
`June 2021 – September 2021`  
**WSU Dormitories**, Pullman, WA  
- Teamed up with elite crews of 3–5 to maintain and restore dorm order.  
- Scrubbed 5+ bathrooms, 5+ common rooms, and crisscrossing halls like a janitorial ninja.

### Manufacturing Technician  
`June 2020 – August 2020`  
**Meter Group Inc.**, Pullman, WA  
- Assembled and tested over 50 parts for 15 different hydrological gizmos.  
- Operated in elite squads of 2–5, balancing speed, precision, and occasional solder burns.

---

## Education

### Computer Science (Machine Learning Focus)  
`January 2024 – July 2028 (Expected)`  
**Brigham Young University–Idaho**, Rexburg, ID  
- Walking the fine line between digital logic and arcane neural wizardry.

---

## Awards

- Survived Bolivia.  
- Made 100 burgers in a day without breaking a sweat.  
- Honored wielder of both a spatula and a needle.

---

<!-- ### Footer

Last updated: [Insert cosmic timestamp here] -->
